//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class TMEMBER
    {
        public int tmembers_ID { get; set; }
        public Nullable<int> teams_ID { get; set; }
        public Nullable<int> emp_ID { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual TEAM1 TEAM { get; set; }
    }
}
